### ISSUE TITLE
Framing Issue with New Drafts Bug

### ISSUE THREAD

**Issue by Catheros** [jamespbarrett/tabletweave#30]
When I hit reset all, the white background of the new 1 tablet, 4 hole, 1 pick draft is narrower than the draft. It continues to be so if I make the draft wider/ taller. If I export as an image, anything that wasn't on top of the white background is cut off, like the edges of the row number
![untitled draft (1)](https://user-images.githubusercontent.com/77672942/142740453-75fe16f8-6a27-4de0-820e-e59643e6dfcb.jpg)
s.

**Comment by jamesba** [comment]
Please specify an exact sequence of actions that produce this effect:

What I do:
What happens:
What should happen:
