### ISSUE TITLE
Repeat Length and Draft Size Interaction Bug

### ISSUE THREAD

**Issue by Catheros** [jamespbarrett/tabletweave#58]
When I have the repeats showing for a long draft, then open another draft with a shorter total length than the repeat length selected for the previous one, the repeats image becomes large, overlaps the main draft and shows the previously opened draft, but with every thread oval \ aligned.
![Screenshot 2024-12-31 120204](https://github.com/user-attachments/assets/a7f032db-35c3-4b7e-8bd1-6d2ae2cc4eff)
![Screenshot 2024-12-31 120335](https://github.com/user-attachments/assets/aa8e0d21-a7b5-49f7-ad64-03d25e0f7539)

**Comment by jamespbarrett** [comment]
Solved in v.1.6.1
