### ISSUE TITLE
Reset All Issue

### ISSUE THREAD

**Issue by Catheros** [jamespbarrett/tabletweave#9]
I have a 67 4-holed tablet, 95 pick draft open at visual scale -4. When I press Reset All, it changes the draft to 1 pick, with 1 4-holed tablet as expected, but the default draft is the same height as the draft I just reset from so it appears huge on the screen. It is at Visual Scale 0 and gets incrementally smaller when I reduce the visual scale. The individual elements also get smaller if I add more picks.

![hoooj](https://user-images.githubusercontent.com/77672942/105030607-ef5f9d80-5a4b-11eb-9c4a-6c3a8b6c7518.jpg)

**Comment by jamesba** [comment]
Cannot replicate.

**Comment by jamesba** [comment]
Caused when ruler location was off the edge of the new draft size before reset/load.

**Comment by jamesba** [comment]
Fixed
